FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/
# Ensure gunicorn is installed for production
RUN pip install --upgrade pip && pip install -r requirements.txt gunicorn

COPY . /app/

EXPOSE 8080
CMD ["gunicorn", "--bind", "0.0.0.0:8080", "core.wsgi:application"]
